stockUi/stockApp/urls.py
from django.conf.urls import url
from stockApp import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns=[

    url(r'^$',views.index,name='index'),

]

stockUi/stockUi/urls.py
from django.contrib import admin
from django.conf.urls import url
from stockApp import views
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^stockApp',include('stockApp.urls')),
    url('admin/', admin.site.urls),
    url(r'^formpage/',views.form_name_view,name='form_name')

]

stockUi/stockApp/models.py
from django.db import models

# Create your models here.

stockUi/stockApp/forms.py
from django import forms

class FormName(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    text=forms.CharField(widget=forms.Textarea)
    s=forms.TextInput()

class stkName(forms.Form):
    CHOICES = (('AXISBANK','Axis Bank Ltd'),('BAJAJ-AUTO','Bajaj Auto Ltd'),('HDFCBANK','HDFC Bank Ltd'),('TCS', 'TCS'),('WIPRO', 'WIPRO'),('TECHM','Tech Mahindra Ltd'),)
    Select = forms.ChoiceField(choices=CHOICES)

'''
Adani Ports and Special Economic Zone Ltd.	ADANIPORTS
Asian Paints Ltd.	ASIANPAINT
Axis Bank Ltd.	AXISBANK
Bajaj Auto Ltd.	BAJAJ-AUTO
Bajaj Finance Ltd.	BAJFINANCE
Bajaj Finserv Ltd.	BAJAJFINSV
Bharat Petroleum Corporation Ltd.	BPCL
Bharti Airtel Ltd.	BHARTIARTL
Bharti Infratel Ltd.	INFRATEL
Britannia Industries Ltd.	BRITANNIA
Cipla Ltd.	CIPLA
Coal India Ltd.	COALINDIA
Dr. Reddy's Laboratories Ltd.	DRREDDY
Eicher Motors Ltd.	EICHERMOT
GAIL (India) Ltd.	GAIL
Grasim Industries Ltd.	GRASIM
HCL Technologies Ltd.	HCLTECH
HDFC Bank Ltd.	HDFCBANK
Hero MotoCorp Ltd.	HEROMOTOCO
Hindalco Industries Ltd.	HINDALCO
Hindustan Unilever Ltd.	HINDUNILVR
Housing Development Finance Corporation Ltd.	HDFC
ICICI Bank Ltd.	ICICIBANK
ITC Ltd.	ITC
Indiabulls Housing Finance Ltd.	IBULHSGFIN
Indian Oil Corporation Ltd.	IOC
IndusInd Bank Ltd.	INDUSINDBK
Infosys Ltd.	INFY
JSW Steel Ltd.	JSWSTEEL
Kotak Mahindra Bank Ltd.	KOTAKBANK
Larsen & Toubro Ltd.	LT
Mahindra & Mahindra Ltd.	M&M
Maruti Suzuki India Ltd.	MARUTI
NTPC Ltd.	NTPC
Oil & Natural Gas Corporation Ltd.	ONGC
Power Grid Corporation of India Ltd.	POWERGRID
Reliance Industries Ltd.	RELIANCE
State Bank of India	SBIN
Sun Pharmaceutical Industries Ltd.	SUNPHARMA
Tata Consultancy Services Ltd.	TCS
Tata Motors Ltd.	TATAMOTORS
Tata Steel Ltd.	TATASTEEL
Tech Mahindra Ltd.	TECHM
Titan Company Ltd.	TITAN
UPL Ltd.	UPL
UltraTech Cement Ltd.	ULTRACEMCO
Vedanta Ltd.	VEDL
Wipro Ltd.	WIPRO
Yes Bank Ltd.	YESBANK
Zee Entertainment Enterprises Ltd.	ZEEL
'''

stockUi/stockApp/views.py
from django.shortcuts import render
from . import forms
from django.http import HttpResponse
import urllib.request
import pandas as pd
import numpy as np
#import matplotlib
#matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.image as plt1
from sklearn.linear_model import LinearRegression
# Create your views here.

def index(request):
    #my_dict = {'insert_me':"Hello i am from views.py"}
    Date=None
    Open=None
    High=None
    Low=None
    Close=None

    arr=None
    arr2=None
    pred=None
    mpred=None
    xlast=None

    p_arr=None
    q_arr2=None
    plast=None
    p_pred=None
    stkP=forms.stkName()

    if request.method=='POST':
        stkP=forms.stkName(request.POST)

    if stkP.is_valid():
        ticker=stkP.cleaned_data['Select']

        url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=NSE:' + ticker + '&apikey=S5R8PAYIH8YYCJAU&datatype=csv'

        def download_stock_data(csv_url):
            response = urllib.request.urlopen(csv_url)
            csv=response.read()
            csv_str=str(csv,'UTF-8')

            lines = csv_str.split("\\n")
            dest_url='templates/dataset.csv'
            fx=open(dest_url,"w")
            for line in lines:
                fx.write(line + "\n")
            fx.close()
        download_stock_data(url)

        dataset=pd.read_csv('templates/dataset.csv')
        xlast=dataset.iloc[:1,4].values
        X = dataset.iloc[1 : ,4  ].values   # /open
        Y = dataset.iloc[0: dataset.shape[0]-1 ,1].values


        # Date=dataset.iloc[:1,0].values
        Date=np.array(dataset.iloc[:1,0].values).tolist()
        Open=np.array(dataset.iloc[:1,1].values).tolist()
        High=np.array(dataset.iloc[:1,2].values).tolist()
        Low=np.array(dataset.iloc[:1,3].values).tolist()
        Close=np.array(dataset.iloc[:1,4].values).tolist()
        Date=Date[0]
        Open=Open[0]
        High=High[0]
        Low=Low[0]
        Close=Close[0]

        print(type(Date[0]))
        print(Date[0])

        X=X.reshape(-1,1)
        Y=Y.reshape(-1,1)

        regressor=LinearRegression()
        regressor.fit(X,Y)

        y_pred = regressor.predict(X[:1,])

        # X=X.ravel();
        # Y=Y.ravel();
        # print(y_pred.ravel())

        # plt.scatter(X.ravel(), Y.ravel(), color='red')
        # plt.plot(X.ravel(), regressor.predict(X).ravel(), color = 'blue')
        # # plt.scatter(y_pred.ravel(),color='green')
        # plt.title('Open vs Close price (Training set)')
        # plt.xlabel('Close price')
        # plt.ylabel('Open')

        # print(type(X.ravel()))




        # plt.savefig('stockApp/static/mysite/images/new_plot.png')

        arr=np.array(X.ravel()).tolist()
        print(type(pred))
        arr2=np.array(Y.ravel()).tolist()
        pred=np.array(y_pred[0].ravel().astype(int).tolist())
        xlast=np.array(X[0].ravel().astype(int).tolist())
        mpred=pred[0]
        # Date=np.array(Date.astype(int))

        # pred=2500
        # xlast=2700
        # print(type(Date.tostring()))

        ###################################     SVR     #########################################################33
        p=dataset.iloc[:-1,1].values
        p=p.reshape(-1,1)
        q=dataset.iloc[:-1,4].values
        q=q.reshape(-1,1)

        print(p[0])


        #data spliting
        '''from sklearn.model_selection import train_test_split
        p_train,p_test,q_train,q_test=train_test_split(p,q,test_size=0.2,random_state=0)
        '''

        from sklearn.preprocessing import StandardScaler
        sc_p = StandardScaler()
        p_train = sc_p.fit_transform(p)
        #p_test = sc_p.transform(p_test)
        sc_q = StandardScaler()
        q_train = sc_q.fit_transform(q)

        # Fitting SVR to the dataset
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'rbf')
        regressor.fit(p_train, q_train)


        # Predicting a new result
        q_pred = regressor.predict(p_train)
        q_pred = sc_q.inverse_transform(q_pred)
        q_pred=q_pred[0]     #closing price of todaq from yesterdays's closing price

        p_arr=np.array(p.ravel()).tolist()
        q_arr2=np.array(q.ravel()).tolist()
        p_pred=q_pred.astype(np.int64)
        # p_pred=np.array(q_pred[0].astype(int).tolist())
        plast=np.array(p[0].ravel().astype(int).tolist())
        print(type(p_pred))

    return render(request,'index.html',{'stkP':stkP,'xx':arr,'yy':arr2,'pred':pred,'mpred':mpred,'xlast':xlast,'Date':Date,'Open':Open,'High':High,'Low':Low,'Close':Close,
                                        'p_arr':p_arr, 'q_arr2':q_arr2, 'p_pred':p_pred,'plast':plast   })



def form_name_view(request):
    form=forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

    if form.is_valid():
        print("VALID")
        print("NAME:" +form.cleaned_data['name'])

    return render(request,'form_page.html',{'form':form})

stockUi/templates/form_page.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>

    <div class="container">
      <form  method="POST">
          {{form.as_p}}
          {% csrf_token %}
        <input type="submit" class="btn btn-primary" name="" value="Submit">
      </form>

      <img src="{% static 'mysite/images.new_plot.png'%}" alt="abx"/>

    </div>
  </body>
</html>

stockUi/templates/index.html
{% load static from staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Stock predict</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <style>

    .asteriskField{
      display: none;
    }
    .col-form-label{
      display: none;
    }
    .bg {
        /* The image used */
        background-image: url({% static 'mysite/images/background.jpeg' %});

        /* Full height */
        height: 100%;

        /* Center and scale the image nicely */
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        opacity: 0.5;
        filter: alpha(opacity=20);
      }

      .heading{
        font-size: 20px;
        text-align: center;
      }
      .tdata{
        text-align: center;
      }

    </style>
    <script>
    // function myFunction() {
    // var x = document.getElementById("myDIV");
    // if (x.style.display === "none") {
    //   x.style.display = "block";
    // }
     // else {
    //   x.style.display = "none";
    // }
  // }


    </script>
  </head>
  <body>

    <!-- {{ insert_me }} -->
  <!-- <div class="bg"> -->


    <div class="container">
      <h1 style="text-align:center; margin-bottom:20px">Stock Prediction</h1>

        <div class="jumbotron ">
          <h1 class="display-4">Welcome User</h1>
          <form method="POST">

            <div>
                <label for="id_Select">Choose a company</label>
              {{stkP|crispy}}
              {% csrf_token %}
            </div>

            &nbsp
            <div class="">
              <input type="submit" class="btn btn-primary" name="" onclick="myFunction()" value="Submit" id="sbt">
            </div>
          </form>

        </div>

        <div style="text-align:center; display:none">
          <img src={% static 'mysite/images/loading.gif' %}>
        </div>
        <div class="current" style="visibility:hidden" id="current">
          <table class="table">
            <thead class="thead-light">
              <tr class="heading">
                <th scope="col"><i style=" margin-right:15px; " class="fas fa-calendar-day"></i>Date</th>
                <th scope="col">Open</th>
                <th scope="col"><i style=" margin-right:15px; color:green" class="fas fa-arrow-alt-circle-up"></i>High</th>
                <th scope="col"><i style=" margin-right:15px; color:red" class="fas fa-arrow-alt-circle-down"></i>Low</th>
                <th scope="col">Close</th>

              </tr>
            </thead>
            <tbody>
              <tr class="tdata">
                <th scope="row">{{Date}}</th>
                <td>{{Open}}</td>
                <td>{{High}}</td>
                <td>{{Low}}</td>
                <td>{{Close}}</td>
              </tr>
            </tbody>
          </table>
        </div>
</div>
<!-- </div> -->
<div class="container" id="pinfo" style="visibility:hidden" >

  <div class=" text-white row" style="padding:5px ; margin:10px; ">
    <div class="col-sm-6 col-md-6 col-lg-6">
      <div class="card-body bg-secondary" style="border-radius:20px">
      The predicted Opening Price for tomorrow is {{mpred}} Rs
      </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6">
      <div class="card-body bg-secondary " style="border-radius:20px">
        The predicted Closing Price for tomorrow is {{p_pred}} Rs
      </div>
    </div>


  </div>
</div>

    <div id="myDIV" class="chart-container container" style=" ">
      <!-- <img src="/static/mysite/images/new_plot.png" alt="Img"> -->
      <canvas id="mixed-chart" ></canvas>
    </div>
    <div class="chart-container container">
      <canvas id="closed-chart"></canvas>
    </div>
      <!-- {{xx}} -->






    <script>

    window.onload=function myFunction() {
      if({{p_pred}}!=='None'){
      document.getElementById("pinfo").style.visibility = 'visible';
      document.getElementById("current").style.visibility = 'visible';
    }
    }

    var ctx = document.getElementById('mixed-chart');


    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels:{{xx}} ,
            datasets: [{
                label: 'Opening Price in Rs',
                data: {{yy}} ,
                backgroundColor: [
                      'rgba(72, 247, 14, 0.2)',
                ],
                borderColor: [
                      'rgba(75, 192, 192, 1)',
                ],
                borderWidth: 1
            },
            {
          label: "Prediction of tomorrow",
          type: "bubble",
          backgroundColor: "rgba(193,46,12,0.6)",
         borderColor: "rgba(193,46,12,1)",
          data: [{
          	x:{{xlast}},
          	y:{{pred}},
          	r:7

          }
          ],
          fill: false
        },

    ]

  },
    //     options: {
    //     scales: {
    //         yAxes: [{
    //             ticks: {
    //                 beginAtZero: false
    //             }
    //         }]
    //     }
    //
    //
    //
    // }


    });


    // Closed chart
    var ctxp = document.getElementById('closed-chart');


    var myChartP = new Chart(ctxp, {
        type: 'line',
        data: {
            labels:{{p_arr}} ,
            datasets: [{
                label: 'Closing Price in Rs',
                data: {{q_arr2}} ,
                backgroundColor: [
                      'rgba(158, 66, 244, 0.2)',
                ],
                borderColor: [
                      'rgba(158, 66, 244, 1)',
                ],
                borderWidth: 1
            },
            {
          label: "Prediction of tomorrow (Closing)",
          type: "bubble",
          backgroundColor: "rgba(192,46,12,0.6)",
         borderColor: "rgba(192,46,12,1)",
          data: [{
          	x:{{plast}},
          	y:{{p_pred}},
          	r:7

          }
          ],
          fill: false
        },

    ]

  },
    //     options: {
    //     scales: {
    //         yAxes: [{
    //             ticks: {
    //                 beginAtZero: false
    //             }
    //         }]
    //     }
    //
    //
    //
    // }


    });

    function abc()
    {



    }
    // alert({{xx}});

    </script>



</html>

stockUi/templates/load.html
<<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <img src="/static/mysite/images/new_plot.png" alt="Img">
  </body>
</html>